spring:
    profiles:
        active:
        - dev
    jpa:
        open-in-view: true

---

taco:
  orders:
    pageSize: 10

spring:
    config:
        activate:
            on-profile: dev
    datasource:
        generate-unique-name: false
        name: tacocloud
    thymeleaf:
        cache: false

logging:
    file:
        path: ./logs/
        file: TacoCloud.log
    level:
        root: INFO
        org:
            springframework:
                security: INFO
        tacos: DEBUG

---

spring:
    config:
        activate:
            on-profile: prod
    datasource:
        url: jdbc:mysql://localhost/tacocloud
        username: tacouser
        password: tacopassword
    

logging:
    level:
        tacos: WARN